CREATE DATABASE chester;

USE chester;

CREATE TABLE Guild(
	ID INT NOT NULL AUTO_INCREMENT,
    DiscordID VARCHAR(128) UNIQUE NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE GuildUser(
	ID INT NOT NULL AUTO_INCREMENT,
    GuildID INT NOT NULL,
    DiscordID VARCHAR(128) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(GuildID) REFERENCES Guild(ID)
)

CREATE TABLE Item (
	ID INT NOT NULL AUTO_INCREMENT,
    GuildID INT NOT NULL,
    ItemName VARCHAR(128) NOT NULL,
    ItemResume VARCHAR(256) NULL,
    ItemDescription VARCHAR(2048) NULL,
    Effect VARCHAR(2048) NULL,
    Weight FLOAT NULL,
    ItemValue FLOAT NULL,
    Secret BOOLEAN NULL,
    CreationDate DATETIME NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(GuildID) REFERENCES Guild(ID)
)

CREATE TABLE Inventory(
	ID INT NOT NULL AUTO_INCREMENT,
    GuildUserID INT NOT NULL,
    InventoryType TINYINT NOT NULL,
    Currency FLOAT NULL,
    MaxWeigth FLOAT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(GuildUserID) REFERENCES GuildUser(ID)
)

CREATE TABLE ItemInstance(
	ID INT NOT NULL AUTO_INCREMENT,
    InventoryID INT NOT NULL,
	ItemID INT NOT NULL,
    Amount FLOAT NOT NULL,
    LastUpdate DATETIME NOT NULL,
    InstanceIndex INT NULL,
	PRIMARY KEY(ID),
    FOREIGN KEY(InventoryID) REFERENCES Inventory(ID),
    FOREIGN KEY(ItemID) REFERENCES Item(ID)
)